#!/usr/bin/env bash
# This script checks the existence and type of a file
if [ -e "$1" ]
then
    echo "school file exists"
    if [ -s "$1" ]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -f "$1" ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
